import { useEffect, useRef, useState } from 'react';
import { MoreHorizontal } from 'lucide-react';
import { actionLabels, lifecycleActions, viewLabels, type LifecycleAction, type LifecycleRecord, type LifecycleView } from './lifecycle-model';

export function LifecycleFilter({ value, onChange, label }: { value: LifecycleView; onChange: (value: LifecycleView) => void; label: string }) {
  return <select aria-label={label} className="input-control text-sm" value={value} onChange={event => onChange(event.target.value as LifecycleView)}>{Object.entries(viewLabels).map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select>;
}
export function LifecycleMenu({ record, disabled, onAction }: { record: LifecycleRecord; disabled?: boolean; onAction: (action: LifecycleAction) => void }) {
  return <details className="relative"><summary aria-label={`Opções de ${record.title}`} className="list-none cursor-pointer p-2 rounded-lg hover:bg-stone-100"><MoreHorizontal className="w-5 h-5" /></summary><div className="absolute right-0 z-20 min-w-48 p-1 bg-white border border-stone-200 rounded-xl shadow-lg">{lifecycleActions(record.lifecycleState).map(action => <button key={action} type="button" disabled={disabled} onClick={event => { event.currentTarget.closest('details')?.removeAttribute('open'); onAction(action); }} className={`block w-full text-left px-3 py-2 text-sm rounded-lg hover:bg-stone-50 disabled:opacity-50 ${action === 'purge' ? 'text-red-700' : 'text-stone-800'}`}>{actionLabels[action]}</button>)}</div></details>;
}
export function LifecycleDialog({ record, action, document, busy, error, onCancel, onConfirm }: { record: LifecycleRecord; action: LifecycleAction; document: boolean; busy: boolean; error?: string | null; onCancel: () => void; onConfirm: (confirmation?: string) => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [confirmation, setConfirmation] = useState('');
  useEffect(() => { const element = dialog.current; element?.showModal(); return () => element?.close(); }, []);
  const irreversible = action === 'purge';
  return <dialog ref={dialog} onCancel={event => { event.preventDefault(); if (!busy) onCancel(); }} className="w-[min(92vw,480px)] p-6 rounded-2xl backdrop:bg-black/35 shadow-xl" aria-labelledby="lifecycle-dialog-title"><h2 id="lifecycle-dialog-title" className="text-xl font-semibold">{actionLabels[action]} {document ? 'documento' : 'caso'}</h2><p className="mt-3 text-sm text-stone-700 break-words">{record.title}</p><p className="mt-3 text-sm text-stone-600">{action === 'archive' ? 'O conteúdo será preservado para consulta. Para voltar a trabalhar, restaure-o. O acesso pela IA será encerrado.' : action === 'trash' ? 'Você poderá restaurar este conteúdo na lixeira. O acesso pela IA será encerrado.' : action === 'restore' ? 'O conteúdo voltará ao estado em que estava antes. Para usar na IA, autorize o acesso novamente.' : document ? 'O texto de todas as versões será removido. As referências nos rascunhos indicarão que a fonte não está mais disponível. Esta ação não pode ser desfeita.' : 'Os documentos, fatos, provas e rascunhos deste caso serão removidos. Esta ação não pode ser desfeita. Os registros de cobrança serão preservados.'}</p>{irreversible && !document && <label className="block mt-4 text-sm">Digite o nome do caso para confirmar<input autoComplete="off" value={confirmation} onChange={event => setConfirmation(event.target.value)} className="input-control w-full mt-2" /></label>}{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<div className="flex justify-end gap-3 mt-6"><button type="button" autoFocus disabled={busy} onClick={onCancel} className="btn-secondary">Cancelar</button><button type="button" disabled={busy || (irreversible && !document && confirmation !== record.title)} onClick={() => onConfirm(irreversible ? document ? record.id : confirmation : undefined)} className={`px-4 py-2 rounded-lg text-white disabled:opacity-50 ${irreversible ? 'bg-red-700' : 'bg-cognac-700'}`}>{busy ? 'Aguarde…' : actionLabels[action]}</button></div></dialog>;
}
