import React from 'react';
import { CreditCard, Info, WalletCards } from 'lucide-react';

export const CreditsScreen: React.FC = () => {
  return <div className="py-8 md:py-12"><div className="page-container space-y-8">
    <div className="border-b border-champagne-border pb-6"><p className="eyebrow">Conta</p><h1 className="font-editorial text-3xl font-bold text-stone-900 sm:text-4xl">Conta e faturamento</h1><p className="mt-1 max-w-2xl text-sm text-stone-500">Consulte créditos e lançamentos somente quando houver uma conta autenticada e dados retornados pelo serviço de faturamento.</p></div>
    <section className="surface p-6 sm:p-8"><div className="flex flex-col items-center gap-4 py-8 text-center"><WalletCards className="h-12 w-12 text-stone-300" aria-hidden="true" /><h2 className="font-editorial text-2xl font-bold text-stone-800">Saldo indisponível</h2><p className="max-w-lg text-sm leading-relaxed text-stone-500">Não há uma conta autenticada ou saldo carregado nesta sessão. Nenhum crédito, bônus ou lançamento contábil é presumido pelo aplicativo.</p><span className="inline-flex items-center gap-2 rounded-lg border border-stone-200 bg-stone-50 px-3 py-2 text-xs font-semibold text-stone-600"><Info className="h-4 w-4" aria-hidden="true" />Dados reais serão exibidos após a conexão com o faturamento</span></div></section>
    <section className="grid grid-cols-1 gap-6 md:grid-cols-2"><div className="surface-subtle p-5"><CreditCard className="h-5 w-5 text-cognac-700" aria-hidden="true" /><h2 className="mt-3 font-editorial text-lg font-bold text-stone-800">Recarga</h2><p className="mt-1 text-sm text-stone-500">A recarga depende de uma operação de pagamento conectada ao backend. Esta interface não simula confirmação, PIX ou crédito de saldo.</p></div><div className="surface-subtle p-5"><WalletCards className="h-5 w-5 text-cognac-700" aria-hidden="true" /><h2 className="mt-3 font-editorial text-lg font-bold text-stone-800">Extrato</h2><p className="mt-1 text-sm text-stone-500">Nenhum lançamento foi carregado. O extrato aparecerá somente após retorno do serviço de faturamento autenticado.</p></div></section>
  </div></div>;
};
