import React, { useState } from 'react';
import { useApp, ApprovalRequest } from '../context/AppContext';
import { ArrowUpRight, CheckCircle, Clock, ShieldAlert, XCircle } from 'lucide-react';

export const DashboardScreen: React.FC = () => {
  const { approvals, resolveApproval, setActiveTab } = useApp();
  const [selectedApproval, setSelectedApproval] = useState<ApprovalRequest | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const pending = approvals.filter((item) => item.status === 'PENDING');
  const resolve = (id: string, action: 'APPROVED' | 'REJECTED') => {
    resolveApproval(id, action); setSelectedApproval(null);
    setMessage(action === 'APPROVED' ? 'Aprovação concedida. A minuta avançou no fluxo.' : 'A minuta foi rejeitada e arquivada para revisão manual.');
    setTimeout(() => setMessage(null), 4000);
  };
  return <div className="py-8 md:py-12"><div className="page-container space-y-8">
    <div className="flex flex-col gap-4 border-b border-champagne-border pb-6 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Revisão</p><h1 className="font-editorial text-3xl font-bold text-stone-900 sm:text-4xl">Revisão do caso</h1><p className="mt-1 max-w-2xl text-sm text-stone-500">Confira pendências reais antes que qualquer conteúdo produza efeito externo.</p></div><button type="button" onClick={() => setActiveTab('matter')} className="btn-primary inline-flex items-center justify-center gap-2">Abrir um caso <ArrowUpRight className="h-4 w-4" aria-hidden="true" /></button></div>
    {message && <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-medium text-emerald-800"><CheckCircle className="mr-2 inline h-5 w-5 text-emerald-600" aria-hidden="true" />{message}</div>}
    <section className="surface space-y-6 p-5 sm:p-6" aria-labelledby="review-queue-title"><div className="flex flex-col gap-2 border-b border-stone-100 pb-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 id="review-queue-title" className="font-editorial text-xl font-bold text-stone-900">Pendências de revisão</h2><p className="mt-1 text-sm text-stone-500">A fila será preenchida quando uma etapa do caso exigir sua conferência.</p></div>{pending.length > 0 && <span className="w-fit rounded-full bg-amber-100 px-3 py-1 text-xs font-semibold text-amber-800">{pending.length} pendente(s)</span>}</div>
      {pending.length === 0 ? <div className="surface-subtle flex flex-col items-center gap-3 p-8 text-center"><CheckCircle className="h-10 w-10 text-emerald-600" aria-hidden="true" /><h3 className="text-base font-semibold text-stone-800">Nenhuma pendência no momento</h3><p className="max-w-md text-sm text-stone-500">Quando um rascunho ou ação exigir aprovação, os detalhes aparecerão aqui para conferência.</p><button type="button" onClick={() => setActiveTab('matter')} className="btn-secondary">Ir para casos</button></div> : <div className="space-y-3">{pending.map((item) => <div key={item.id} className="space-y-3 rounded-xl border border-amber-200 bg-amber-50/40 p-4"><div className="flex items-start justify-between gap-3"><div><span className="rounded bg-amber-200/60 px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-amber-800">{item.court}</span><h3 className="mt-1 text-sm font-bold text-stone-900">{item.title}</h3></div><span className="flex shrink-0 items-center text-[10px] text-stone-400"><Clock className="mr-1 h-3 w-3" aria-hidden="true" />{item.requestedAt}</span></div><p className="text-sm text-stone-600">{item.description}</p><div className="flex gap-2"><button type="button" onClick={() => setSelectedApproval(item)} className="btn-secondary flex-1">Revisar minuta</button><button type="button" onClick={() => resolve(item.id, 'APPROVED')} className="rounded-lg bg-emerald-600 px-3 py-2 text-xs font-semibold text-white">Aprovar</button></div></div>)}</div>}
    </section>
    {selectedApproval && <div className="fixed inset-0 z-50 flex items-center justify-center bg-stone-900/60 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="approval-title"><div className="surface max-h-[90vh] w-full max-w-3xl space-y-6 overflow-y-auto p-6 sm:p-8"><div className="flex items-start justify-between border-b border-stone-100 pb-4"><div><span className="rounded-md bg-amber-100 px-2.5 py-0.5 text-xs font-bold text-amber-800">Efeito externo condicionado à sua aprovação</span><h2 id="approval-title" className="mt-2 font-editorial text-xl font-bold text-stone-900">{selectedApproval.title}</h2><p className="mt-1 text-xs text-stone-500">Destino: {selectedApproval.court} · Requisitado em {selectedApproval.requestedAt}</p></div><button type="button" onClick={() => setSelectedApproval(null)} className="rounded-lg bg-stone-100 px-3 py-2 text-stone-600" aria-label="Fechar revisão">×</button></div><div><p className="mb-2 text-xs font-bold uppercase tracking-wider text-stone-500">Conteúdo da minuta</p><div className="max-h-72 overflow-y-auto rounded-xl border border-champagne-border bg-[#FDFBF7] p-5 font-serif text-sm leading-relaxed text-stone-800 whitespace-pre-wrap">{selectedApproval.draftContent}</div></div><div className="flex items-start gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs text-amber-900"><ShieldAlert className="h-5 w-5 shrink-0 text-amber-700" aria-hidden="true" /><span><strong>Conferência humana:</strong> ao aprovar, você confirma o conteúdo e autoriza o próximo passo do fluxo.</span></div><div className="flex flex-col-reverse gap-3 pt-2 sm:flex-row sm:items-center sm:justify-between"><button type="button" onClick={() => resolve(selectedApproval.id, 'REJECTED')} className="inline-flex items-center justify-center gap-1.5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-2.5 text-sm font-semibold text-rose-700"><XCircle className="h-4 w-4" aria-hidden="true" />Rejeitar minuta</button><div className="flex justify-end gap-3"><button type="button" onClick={() => setSelectedApproval(null)} className="btn-secondary">Voltar</button><button type="button" onClick={() => resolve(selectedApproval.id, 'APPROVED')} className="rounded-xl bg-emerald-600 px-5 py-2.5 text-sm font-semibold text-white">Aprovar e continuar</button></div></div></div></div>}
  </div></div>;
};
