import { useEffect, useState } from 'react';
import { getBillingAccount } from '../api-client';
import { HostInstallationGuide } from './connections/HostInstallationGuide';
import { resolveMcpUrl, type HostPlatform } from './connections/connection-model';

export function formatSearchCost(searchCostCents: number | null): string {
  return searchCostCents === null ? 'Consulte a conta para ver o custo atualizado da pesquisa.' : `${new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(searchCostCents / 100)} por pesquisa jurisprudencial`;
}

export function ForLawyersGuideScreen() {
  const [platform, setPlatform] = useState<HostPlatform>('chatgpt');
  const [searchCostCents, setSearchCostCents] = useState<number | null>(null);
  useEffect(() => { let active = true; void getBillingAccount().then((data) => { if (active) setSearchCostCents(data.searchCostCents); }).catch(() => { if (active) setSearchCostCents(null); }); return () => { active = false; }; }, []);
  return <div className="py-8 md:py-12"><div className="page-container space-y-8">
    <header className="border-b border-champagne-border pb-6"><p className="eyebrow">Guia de conexão</p><h1 className="mt-2 font-editorial text-3xl font-bold text-stone-900 sm:text-4xl">Guia de conexão para advogados</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-stone-600">Instale as ferramentas de pesquisa jurídica do ForgeLex no ChatGPT ou Claude. Este roteiro cobre configuração, autorização, primeira consulta e revogação.</p></header>
    <nav aria-label="Plataforma do guia" className="flex gap-2">{(['chatgpt', 'claude'] as const).map((host) => <button key={host} type="button" aria-pressed={platform === host} className={platform === host ? 'btn-primary' : 'btn-secondary'} onClick={() => setPlatform(host)}>{host === 'chatgpt' ? 'ChatGPT' : 'Claude'}</button>)}</nav>
    <HostInstallationGuide platform={platform} mcpUrl={resolveMcpUrl()} />
    <section className="surface p-6 sm:p-8"><h2 className="font-editorial text-2xl font-bold text-stone-900">Confirme o funcionamento</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-stone-600">Na conversa com o ForgeLex habilitado, solicite uma pesquisa, abra um resultado e confira a fonte. A pesquisa consome créditos; as etapas seguintes são gratuitas. Para testar sem gastar créditos, peça: “Execute a ferramenta forgelex.connection_status e mostre o resultado.” Essa verificação gratuita deve ser feita na conversa do aplicativo.</p><ol className="mt-5 space-y-4 border-l border-stone-200 pl-5 text-sm leading-7 text-stone-700"><li><strong>Pesquisar:</strong> “Use o ForgeLex para pesquisar jurisprudência do STJ sobre responsabilidade civil por vazamento de dados. Mostre os identificadores e as fontes dos resultados.”</li><li><strong>Abrir:</strong> “Abra no ForgeLex a autoridade de identificador [identificador retornado]. Mostre o texto e a proveniência disponíveis.”</li><li><strong>Verificar:</strong> “Verifique no ForgeLex a autoridade [identificador retornado] e explique o resultado da verificação.”</li></ol><p className="mt-5 text-sm text-stone-600">O aplicativo deve mostrar uma chamada às ferramentas ForgeLex. Uma resposta de texto do modelo, sem chamada à ferramenta, não comprova uso da integração.</p></section>
    <section className="surface p-6 sm:p-8"><h2 className="font-editorial text-2xl font-bold text-stone-900">Se a conexão falhar</h2><dl className="mt-5 space-y-5 text-sm leading-7"><div><dt className="font-semibold text-stone-900">“Não foi possível descobrir as configurações do OAuth”</dt><dd className="text-stone-600">A descoberta da autenticação falhou. Confira a URL, incluindo /mcp. Se ela estiver correta, a correção é do servidor ForgeLex; não selecione “Sem autenticação” nem exponha uma chave na URL.</dd></div><div><dt className="font-semibold text-stone-900">Solicitação expirada ou acesso recusado</dt><dd className="text-stone-600">Inicie uma nova conexão pelo aplicativo e autorize novamente. Se você revogou o acesso, a autorização anterior deixa de servir.</dd></div><div><dt className="font-semibold text-stone-900">Ferramentas não aparecem ou não são chamadas</dt><dd className="text-stone-600">Selecione o ForgeLex no menu de ferramentas da conversa. Após uma atualização, atualize a conexão no aplicativo e abra uma nova conversa.</dd></div><div><dt className="font-semibold text-stone-900">Pesquisa informa crédito insuficiente</dt><dd className="text-stone-600">A autenticação pode estar funcionando; a operação foi bloqueada pelo saldo. Confira <a className="font-semibold text-cognac-800 underline" href="/conta">créditos e tarifa na conta</a>. {formatSearchCost(searchCostCents)}</dd></div></dl></section>
    <section className="surface p-6 sm:p-8"><h2 className="font-editorial text-2xl font-bold text-stone-900">Como revogar</h2><p className="mt-3 text-sm leading-7 text-stone-600">Abra <a className="font-semibold text-cognac-800 underline" href="/conectar">Conectar IA → Aplicativos autorizados</a> e revogue o aplicativo. Remova também a conexão no ChatGPT ou Claude. Chaves de API criadas separadamente são administradas em <a className="font-semibold text-cognac-800 underline" href="/conta/chaves">Chaves de API</a>.</p><p className="mt-4 text-sm leading-7 text-stone-600">O ForgeLex recebe a chamada autenticada e os argumentos enviados à ferramenta. O host fornece o modelo e mantém seus próprios custos; ele pode enviar trechos da pergunta como argumentos da pesquisa.</p></section>
    <footer className="flex flex-wrap gap-3"><a className="btn-secondary min-h-11" href="/conta">Ir para a conta</a><a className="btn-secondary min-h-11" href="/conta/chaves">Gerenciar chaves de API</a></footer>
  </div></div>;
}
